# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Configure aws credentials for test 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      # Runs a set of commands using the runners shell
      - name: "Run Migrations"
        run: |
          ssh-keygen -t rsa -q -N “” -f test <<<y >/dev/null 2>&1
          
          aws ec2-instance-connect send-ssh-public-key --instance-id i-0fb9ba4840e9e4b36 --availability-zone us-west-2a --instance-os-user ec2-user --ssh-public-key file://test.pub
          
          ssh -i test -Nf -M -L ${{ secrets.DEV_DB_STRING }} -o “UserKnownHostsFile /dev/null” -o “StrictHostKeyChecking no” -o “ProxyCommand aws ssm start-session --target %h --document AWS-StartSSHSession --parameters portNumber=%p --region=us-west-2" ec2-user@i-0fb9ba4840e9e4b36
          
          netstat -tnpa | grep 'ESTABLISHED.*sshd'
